solve duplicate ID when generating typescript model
Rhetos/AdminGui pull request #36
Opened 2018-10-15 06:54 UTC by thanhlm91

generate definition & initialization of field 'ID' by passing parameter instead of hard code
skip generating field 'ID' of simpler data structures

2018-10-15 06:56 UTC, thanhlm91 commented
workaround solution to solve issue #36

2018-10-15 07:09 UTC, thanhlm91 commented
@bantolov 

As discussion with @nguyenquanghuy031295, we couldn't figure out how to solve issue #36 effectively as there is no way to detect entities have property 'ID' defined or not. Our workaround solution is just skip generating field 'ID' of simpler data structures.

In addition, there is no way to generate property 'ID' as other types than String as we found property 'ID' in generated ts models have to be String type as they extend BaseCode.

2018-10-15 08:43 UTC, bantolov requested changes

2018-10-15 08:43 UTC, bantolov commented on Plugins/AdminGuiPlugin/Angular2ModelGenerator/Generators/Entities/DataStructureGenerator.cs
> +            return ConceptKeywords.SimplerDataStructures.Contains(info.GetType().GetCustomAttribute<ConceptKeywordAttribute>()?.Keyword);
Checking for simple data structures by keyword does include for the derivations of these concepts (custom data structure concepts on our projects are often used and they are always derived from existing ones as far as I know). I think would be best to reverse the logic here and list the concepts with ID property, then check if the `info` is a derivation of such concept (probably with  Type.IsAssignableFrom method).

I have search the data structure concepts in the CommonConcepts, the concepts with ID that we should check here: PolymorphicInfo, ComputedInfo, QueryableExtensionInfo, SqlQueryableInfo, LegacyEntityWithAutoCreatedViewInfo, LegacyEntityInfo, BrowseDataStructureInfo, EntityInfo.

2018-10-16 09:41 UTC, bantolov approved these changes

2018-10-16 09:53 UTC, merged